version: '3.8'

services:
  web:
    image: krammm/php-app:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html # Mount application code into the container
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laundry_service
      MYSQL_USER: app_user
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
